env:
  browser: true
  es6: true
  node: true
  googleappsscript/googleappsscript: true
extends: "eslint:recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - off
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
plugins:
  - googleappsscript
