// please refer to naming conventions
// "https"://github.com/rankingdigitalrights/datalab/blob/pilot-fork/clasp-proj/docs/dictionary.MD

const companiesVector = {
  collection: 'companies',
  indexYear: 2021,
  indexType: 'RDR Index',
  lastRevised: '2021-03-12',
  companies: [
    {
      id: 'iAL1',
      label: {
        current: 'Alibaba',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Alibaba',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2020,
      columnPrevOutcomeStart: 'V',
      columnPrevOutcomeEnd: 'Y',
      urlPrevInputSheet: '1WmI5QXq2p4tVY3JdfFV8Ra5DV3wp7bhH6ufo2Mzpkhw',
      urlCurrentInputSheet: '1k0JXkI0YBL-SjofLnE4xq5Ob9R72bE2j_7qPczfEeaA',
      urlPrevOutputSheet: '10kB6eIKaSft7le_Jw_jQ-m6V3w_Q4KxS_2ifK3ebt7g',
      urlCurrentOutputSheet: '1X7rk682S2igHqbeZcJ-OVdnss_MyMMgHl_TqlYfb56k',
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1a50nKAhi14oEoh5Hxba4iZQNFg0A3IUT8vohGfLPfH0',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'ecAL1',
          type: 'eCommerce',
          label: {
            current: 'Taobao.com',
            legacy: [null],
          },
        },
        {
          id: 'ebAL1',
          type: 'pda',
          label: {
            current: 'AliGenie',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'iAZ1',
      label: {
        current: 'Amazon',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Amazon',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2020,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '1B35t-vsT4E-PCg5MKCHwBOj3o3XwYYVUuDrZKg756sQ',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1ynSoO0rLhnaorj1kX0S0NtVFQJOCuBatwMo-td9VVLU',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1jEl6aapmghkdc51Ki78lIzJvSoNg_FVTigGGImQ7tIQ',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'ecAZ1',
          type: 'eCommerce',
          label: {
            current: 'Amazon.com',
            legacy: [null],
          },
        },
        {
          id: 'ebAZ1',
          type: 'pda',
          label: {
            current: 'Alexa',
            legacy: [null],
          },
        },
        {
          id: 'clAZ1',
          type: 'cloud',
          label: {
            current: 'Amazon Drive',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'tAM1',
      label: {
        current: 'América Móvil',
        altFilename: 'AmericaMovil',
        legacy: [null],
      },
      type: 'telecom',
      groupLabel: 'América Móvil (Group)',
      hasOpCom: true,
      opComLabel: 'Telcel (Operating Company)',
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'V',
      columnPrevOutcomeEnd: 'Y',
      urlPrevInputSheet: '1UwQa0iIfWcEFW6cRxlmw-Sfw3qvs3bwQQ5vwmptrD8o',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1cRT_I5me7moYN3p6DR4Y8ssTd1xXKgrMrvf2wTxmwyQ',
      urlCurrentOutputSheet: '18URZmKH8UCFshaXkjGXZmiP0rGBZph6TLWPvIr-ev2A',
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1kPMGzJZoPjuOFqkg7R9ODi8vy9NCwNP3l-ngYoSLUW0',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'mbAM1',
          type: 'mobile',
          subtype: 'prepaid',
          label: {
            current: 'Prepaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'mbAM2',
          type: 'mobile',
          subtype: 'postpaid',
          label: {
            current: 'Postpaid mobile',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'iAP1',
      label: {
        current: 'Apple',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Apple',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2017,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '1tvk9IH-BJ5QL-MWrAG-pHURXLVsodnG_XIKZtSK6SP0',
      urlCurrentInputSheet: '1FZUZhEPTegWXqjkR5ZoBevyIHsCjkIl4DnBtitlLajA',
      urlPrevOutputSheet: '17YVnTQrPZc-OcKQCN4hvvzGYjJ9GRIF783xs-u3c47o',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1H5vklBAtRWz9INVWr5lvoLn41Hp6Wfyu9Jcii6mRS9E',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'meAP1',
          type: 'mobileEcosystem',
          label: {
            current: 'iOS (mobile ecosystem)',
            legacy: ['iOS mobile ecosystem'],
          },
        },
        {
          id: 'mvAP1',
          type: 'messagingVoip',
          label: {
            current: 'iMessage',
            legacy: [null],
          },
        },
        {
          id: 'clAP1',
          type: 'cloud',
          label: {
            current: 'iCloud',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'tAT1',
      label: {
        current: 'AT&T',
        altFilename: 'ATT',
        legacy: [null],
      },
      type: 'telecom',
      groupLabel: 'AT&T (Group)',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '1KGJUM95bNuvFDzZqXpZaDKbwMa379_HDvff7Rg4Wc3k',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1l0XO3oiPo_Ffzf-cSbfm9ynJ30kWsVn6_QiXO4G76CI',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1sNnrGmHyRsjlgfWbItDc-bRKmfOnLZQdwlwhAXlLe30',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'mbAT1',
          type: 'mobile',
          subtype: 'prepaid',
          label: {
            current: 'Prepaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'mbAT2',
          type: 'mobile',
          subtype: 'postpaid',
          label: {
            current: 'Postpaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'bbAT1',
          type: 'broadband',
          label: {
            current: 'Fixed-line broadband',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'tAX1',
      label: {
        current: 'Axiata',
        altFilename: null,
        legacy: [null],
      },
      type: 'telecom',
      groupLabel: 'Axiata (Group)',
      hasOpCom: true,
      opComLabel: 'Celcom (Operating Company)',
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '1bi7WVri0AsI0wqOjQ9XNQXeW_KZ1FuEz-mkBGiLE3Cc',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1tGDUSlM68H6PFNtDAgBg53JD-cp6plzcqWLCpR0s4oI',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1q7aG-ziQi0vVQBvpYSZPkNOnTJtpRMjDoBHVKrKrBTA',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'mbAX1',
          type: 'mobile',
          subtype: 'prepaid',
          label: {
            current: 'Prepaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'mbAX2',
          type: 'mobile',
          subtype: 'postpaid',
          label: {
            current: 'Postpaid mobile',
            legacy: [null],
          },
        },
        {
          isNewService: true,
          id: 'bbAX1',
          type: 'broadband',
          label: {
            current: 'Fixed-line broadband',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'iBA1',
      label: {
        current: 'Baidu',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Baidu',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2017,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '17LIVa6Mj2ARm7E7aRHmIdvaD0UWxY4SA0C5YY166GBE',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1vZ9kDPaNRqQ-o3ckskuwX6mu5hjnlYi8Qo06ExpMEJs',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1SsVuZ2VIX9EIBikjPF0PfQYurfPg2q82yrVRKXg_xsI',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'seBA1',
          type: 'search',
          label: {
            current: 'Baidu Search',
            legacy: [null],
          },
        },
        {
          id: 'clBA1',
          type: 'cloud',
          label: {
            current: 'Baidu Cloud',
            legacy: [null],
          },
        },
        {
          id: 'mvBA1',
          type: 'socialNetworkBlogs',
          label: {
            current: 'Baidu PostBar',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'tBH1',
      label: {
        current: 'Bharti Airtel',
        altFilename: null,
        legacy: [null],
      },
      type: 'telecom',
      groupLabel: 'Bharti Airtel (Group)',
      hasOpCom: true,
      opComLabel: 'Airtel India (Operating Company)',
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '1pz7nE153onnNfDPqoPXI_D2V5ZLMNip7g8r6s0OpybQ',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '11xYk6eYpwPSZW6TAXtEWqxcfIfuevNDFz0d_zSZa1-I',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1gegrdeFVFW-J4UqClvmRl58WWabNnolsdi9uQsUqjsc',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'mbBH1',
          type: 'mobile',
          subtype: 'prepaid',
          label: {
            current: 'Prepaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'mbBH2',
          type: 'mobile',
          subtype: 'postpaid',
          label: {
            current: 'Postpaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'bbBH1',
          type: 'broadband',
          label: {
            current: 'Fixed-line broadband',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'tDT1',
      label: {
        current: 'Deutsche Telekom',
        altFilename: 'DeutscheTelekom',
        legacy: [null],
      },
      type: 'telecom',
      groupLabel: 'Deutsche Telekom (Group)',
      hasOpCom: true,
      opComLabel: 'Deutsche Telekom (Operating Company)',
      isPrevScored: true,
      firstIndex: 2019,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '1qHXyuNG5S52jb02gdcHq9cdc5mTsuaI4-v8GgSi4sFA',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1NIzkuylsr_2zkK8H7eh8UiJbmBZIs9ul48eod-sLcxU',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1kBFsD1cLNW1v2YyVYxobC0PyJwxfmEUmPATGGUV44r4',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'mbDT1',
          type: 'mobile',
          subtype: 'prepaid',
          label: {
            current: 'Prepaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'mbDT2',
          type: 'mobile',
          subtype: 'postpaid',
          label: {
            current: 'Postpaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'bbDT1',
          type: 'broadband',
          label: {
            current: 'Fixed-line broadband',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'tET1',
      label: {
        current: 'Etisalat',
        altFilename: null,
        legacy: [null],
      },
      type: 'telecom',
      groupLabel: 'Etisalat (Group)',
      hasOpCom: true,
      opComLabel: 'Etisalat UAE (Operating Company)',
      isPrevScored: true,
      firstIndex: 2019,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '1G4PznxQg_h_xMi5JJOIyHd8N47Waa508RcblC9Sfz94',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '19X9iO4Q6uoW5CJ_K39v_llZJ59dj2HazHkux2WrXMPQ',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1FpbkqeozMf-YGqfA17PfY0X38mLcUXfzafEcf_Y5Vmw',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'mbET1',
          type: 'mobile',
          subtype: 'prepaid',
          label: {
            current: 'Prepaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'mbET2',
          type: 'mobile',
          subtype: 'postpaid',
          label: {
            current: 'Postpaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'bbET1',
          type: 'broadband',
          label: {
            current: 'Fixed-line broadband',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'iFB1',
      label: {
        current: 'Facebook',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Facebook (Group)',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'AD',
      columnPrevOutcomeEnd: 'AI',
      urlPrevInputSheet: '1LkJlcXq3wx4cInqjaxpqC3Udf8MeGvzX607RCWtCffw',
      urlCurrentInputSheet: '1a-MOaG1a4NrPnKrulJayvZEVoW6t_Cl51xX0X7ltd00',
      urlPrevOutputSheet: '12TvSEnAQURFoWGWTBEkUrrmORs_Zdz9cDhd9h3qH0eU',
      urlCurrentOutputSheet: '1xtn8CMuW0MFWclZr37Qe-4qxK1C5VCd6xfJaX_JFn1o',
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1mKA6erBPbTMu5DYiz6wqhLbMQ11-uxk36cPoFTsqw0o',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'snFB1',
          type: 'socialNetworkBlogs',
          label: {
            current: 'Facebook',
            legacy: [null],
          },
        },
        {
          id: 'pvFB1',
          type: 'photoVideo',
          label: {
            current: 'Instagram',
            legacy: [null],
          },
        },
        {
          id: 'mvFB1',
          type: 'messagingVoip',
          label: {
            current: 'WhatsApp',
            legacy: [null],
          },
        },
        {
          id: 'mvFB2',
          type: 'messagingVoip',
          label: {
            current: 'Messenger',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'iGO1',
      label: {
        current: 'Google',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Google (Group)',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'AH',
      columnPrevOutcomeEnd: 'AN',
      urlPrevInputSheet: '1tkOrgUWe0sG5cfNYeoph5IQdYt_A3LGbR2JMkCdwhGg',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1yizjORRCaxzvc8yQD8JrQ-gzW8RaVlK4HRA_Pc990gI',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1e1MsG6euhGvNXj12E5KAwvH70QBTwdFe3uI7C0TvyPs',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'seGO1',
          type: 'search',
          label: {
            current: 'Google Search',
            legacy: ['Search'],
          },
        },
        {
          id: 'emGO1',
          type: 'email',
          label: {
            current: 'Gmail',
            legacy: [null],
          },
        },
        {
          id: 'pvGO1',
          type: 'photoVideo',
          label: {
            current: 'YouTube',
            legacy: [null],
          },
        },
        {
          id: 'meGO1',
          type: 'mobileEcosystem',
          label: {
            current: 'Android mobile ecosystem',
            legacy: [null],
          },
        },
        {
          id: 'clGO1',
          type: 'cloud',
          label: {
            current: 'Google Drive',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'iKA1',
      label: {
        current: 'Kakao',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Kakao (Group)',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '1Ld1w8GS3Rn7AncE3AQBx5z4Ad5ww4lL0xe3lhlVDLu4',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1Fdc0UotXXgWV84lTWJaP9rl9wCY5c5o49wswMF5VVcc',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1emUUw9pUzjBPEqatrQFzGWqoG8F0wGHR4ywvmQYDmFA',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'seKA1',
          type: 'search',
          label: {
            current: 'Daum Search',
            legacy: ['Kakao Search'],
          },
        },
        {
          id: 'emKA1',
          type: 'email',
          label: {
            current: 'Daum Mail',
            legacy: [null],
          },
        },
        {
          id: 'mvKA1',
          type: 'messagingVoip',
          label: {
            current: 'KakaoTalk',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'iMA1',
      label: {
        current: 'Mail.Ru',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Mail.Ru (Group)',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'AD',
      columnPrevOutcomeEnd: 'AI',
      urlPrevInputSheet: '1qYiP2KP2xB7SRM1br6LunjF6PoqWvGoCIeE8G8hXbB4',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1oLxTggmytYBvigz6k97-zPkfT2LX47KGhj9TeIE1NV0',
      urlCurrentOutputSheet: '17sVWRlTfn_KR-QN5m9b0ZlnkWXqi6KZNcm6Q0-H-2gY',
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1U_OOQpcSK_p66UyXWXyFPXddKN9Ez9kidZgnUXEyaIM',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'snMA1',
          type: 'socialNetworkBlogs',
          label: {
            current: 'VK',
            legacy: [null],
          },
        },
        {
          id: 'emMA1',
          type: 'email',
          label: {
            current: 'Mail.Ru email',
            legacy: [null],
          },
        },
        {
          id: 'mvMA1',
          type: 'messagingVoip',
          label: {
            current: 'Mail.Ru Agent',
            legacy: [null],
          },
        },
        {
          id: 'clMA1',
          type: 'cloud',
          label: {
            current: 'Mail.Ru Cloud Solutions',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'iMS1',
      label: {
        current: 'Microsoft',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Microsoft',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'AD',
      columnPrevOutcomeEnd: 'AI',
      urlPrevInputSheet: '1Bw5YfKfBMcLNca39qc7vye42vd_Zk5V2lM_8RYGRSAE',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1X2-cvOtXuq0Ex8oiIHFKYKhBVeTkS92Pcqm3tIofqc8',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1NfQRjLQeeOOqtsNpJDtpl3DOwAUYKvbpqqi2iupbU4s',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'seMS1',
          type: 'search',
          label: {
            current: 'Bing',
            legacy: ['Bing (search)'],
          },
        },
        {
          id: 'emMS1',
          type: 'email',
          label: {
            current: 'Outlook.com',
            legacy: [null],
          },
        },
        {
          id: 'mvMS1',
          type: 'messagingVoip',
          label: {
            current: 'Skype',
            legacy: [null],
          },
        },
        {
          id: 'clMS1',
          type: 'cloud',
          label: {
            current: 'OneDrive',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'tMT1',
      label: {
        current: 'MTN',
        altFilename: null,
        legacy: [null],
      },
      type: 'telecom',
      groupLabel: 'MTN',
      hasOpCom: true,
      opComLabel: 'MTN South Africa',
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '1KjK1n2SbLkxGYmu7iIF7N5cScIYHm8pvJzGB89UemtI',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1B-Lhd1vEhUzdwfqX-TucZV1qjxArDiK-zLGbfbsf9gg',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1oi-ePx4y7n25A-fuXujK1rwAfP0o0fVIISjsJB4wK2E',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'mbMT1',
          type: 'mobile',
          subtype: 'prepaid',
          label: {
            current: 'Prepaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'mbMT2',
          type: 'mobile',
          subtype: 'postpaid',
          label: {
            current: 'Postpaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'bbMT1',
          type: 'broadband',
          label: {
            current: 'Fixed-line broadband',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'tOD1',
      label: {
        current: 'Ooredoo',
        altFilename: 'Ooredoo',
        legacy: [null],
      },
      type: 'telecom',
      groupLabel: 'Ooredoo (Group)',
      hasOpCom: true,
      opComLabel: 'Ooredoo Qatar',
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '18nbBe8yAIF2vjwZjioohW1BoiYPg9OE916-1pWT7Stk',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1HBt3nm9qVBbfbAOgqbB2lYpM8nOmBV0uB2v-JXZX4lQ',
      urlCurrentOutputSheet: '16DXAV0i1IZ17CInTw7j_1R2QM3qW0Drso5btg91Lu-o',
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1iLiZv6JL_RTfO4XJGyGYACak-BEhXDxQ7edLj2_SrtI',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'mbOD1',
          type: 'mobile',
          subtype: 'prepaid',
          label: {
            current: 'Prepaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'mbOD2',
          type: 'mobile',
          subtype: 'postpaid',
          label: {
            current: 'Postpaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'bbOD1',
          type: 'broadband',
          label: {
            current: 'Fixed-line broadband',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'tOR1',
      label: {
        current: 'Orange',
        altFilename: 'Orange',
        legacy: [null],
      },
      type: 'telecom',
      groupLabel: 'Orange',
      hasOpCom: true,
      opComLabel: 'Orange France',
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '12hQjVpLb3i3WxVYNEzUqdZyBncI6L69MO3e7iMYfIck',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1S1MFdcMo0CdrplDADwtgqv_nRcXgfDimZqzYiRk3Ass',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1ombvC3x2n25_84R8Mz8vXD0TJ6iHUo5UgeIODB8vMUo',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'mbOR1',
          type: 'mobile',
          subtype: 'prepaid',
          label: {
            current: 'Prepaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'mbOR2',
          type: 'mobile',
          subtype: 'postpaid',
          label: {
            current: 'Postpaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'bbOR1',
          type: 'broadband',
          label: {
            current: 'Fixed-line broadband',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'iSA1',
      label: {
        current: 'Samsung',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Samsung (Group)',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2017,
      columnPrevOutcomeStart: 'V',
      columnPrevOutcomeEnd: 'Y',
      urlPrevInputSheet: '116hQwK-fOJF46G4XmK-FpiSHpQbUeD4XXWc9Cx-8Euk',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '12plehZS80RuiGSen7QsPFVY2vjtG9smC6FjknXcFZIY',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1RmYTNyzRMJ63l8IpVEwrMNVpY7GIkAH2TQYLehSToZw',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'meSA1',
          type: 'mobileEcosystem',
          label: {
            current: 'Samsung implementation of Android',
            legacy: [null],
          },
        },
        {
          id: 'clSA1',
          type: 'cloud',
          label: {
            current: 'Samsung Cloud',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'tTF1',
      label: {
        current: 'Telefónica',
        altFilename: 'Telefonica',
        legacy: [null],
      },
      type: 'telecom',
      groupLabel: 'Telefónica',
      hasOpCom: true,
      opComLabel: 'Telefónica Spain',
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '1pF6YV_FzlKr6sHbV3Id8pV9rouD9Rs6r9g-fcBGlmj4',
      urlCurrentInputSheet: '1GhQTF8rjYOFQ7u9nXh-MrJFSkDaJPK_MMrP2ERpxRGw',
      urlPrevOutputSheet: '1YT4I-A58Z5gaDjpxr_SLIXtG5zjbfQcmK-AL2URM5sw',
      urlCurrentOutputSheet: '1P0RFamrdD6jMfX5ONGR_bGfHTZRwRyTLHYp6c0UgEhw',
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1RsNd0lons-btB7nOEH6Tgr3PDLArNcPLXF4O9HzpOlo',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'mbTF1',
          type: 'mobile',
          subtype: 'prepaid',
          label: {
            current: 'Prepaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'mbTF2',
          type: 'mobile',
          subtype: 'postpaid',
          label: {
            current: 'Postpaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'bbTF1',
          type: 'broadband',
          label: {
            current: 'Fixed-line broadband',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'tTN1',
      label: {
        current: 'Telenor',
        altFilename: null,
        legacy: [null],
      },
      type: 'telecom',
      groupLabel: 'Telenor',
      hasOpCom: true,
      opComLabel: 'Telenor (Operating Company)',
      isPrevScored: true,
      firstIndex: 2019,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '150kTM3p6zcigywbRIUaki9NLtXmKEFHGRY2fNMDhSBk',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1UOzidB_ECjpu1BFChzeSkJpUMutRL1A6kE86pJr1cD4',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1PBecu3rYlDfKpYeLTMZo_M67OqVfo0KkYg2GjloLz0Q',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'mbTN1',
          type: 'mobile',
          subtype: 'prepaid',
          label: {
            current: 'Prepaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'mbTN2',
          type: 'mobile',
          subtype: 'postpaid',
          label: {
            current: 'Postpaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'bbTN1',
          type: 'broadband',
          label: {
            current: 'Fixed-line broadband',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'iTC1',
      label: {
        current: 'Tencent',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Tencent (Group)',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2017,
      columnPrevOutcomeStart: 'AD',
      columnPrevOutcomeEnd: 'AI',
      urlPrevInputSheet: '1LxyBnEMep0OP9r-jOGTMLaIRmizOaHHDwNSTbWJ1wHg',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1GLSFkoSYzatMOaRQjNyGbkgJEWZbTtatZsASxcH5LYs',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1rUGzQl68AAsS3CL2Senabd9LVciTZY5P8b26YaESHL8',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'snTC1',
          type: 'socialNetworkBlogs',
          label: {
            current: 'QZone',
            legacy: [null],
          },
        },
        {
          id: 'mvTC1',
          type: 'messagingVoip',
          label: {
            current: 'QQ',
            legacy: [null],
          },
        },
        {
          id: 'mvTC2',
          type: 'messagingVoip',
          label: {
            current: 'WeChat',
            legacy: [null],
          },
        },
        {
          id: 'clTC1',
          type: 'cloud',
          label: {
            current: 'Tencent Cloud',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'iTW1',
      label: {
        current: 'Twitter',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Twitter',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'R',
      columnPrevOutcomeEnd: 'T',
      urlPrevInputSheet: '18_EcR5oZIdF-UvP47kLlD1Lj8U8ES1DdbVlLaitjwfI',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1DxsufAJtnphzfdSs5GDMw5mYfjK99_Z3U5AZvAg1FTM',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1hc-jQp9rds3e6FnZiyLA-gKcIHlmpKaEjrwJYP2IQgw',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'smTW1',
          type: 'socialNetworkBlogs',
          label: {
            current: 'Twitter',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'iVM1',
      label: {
        current: 'Verizon Media',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Verizon Media',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'R',
      columnPrevOutcomeEnd: 'T',
      urlPrevInputSheet: '1lLXsyxGnIlTf3tSMTtrJObxy6hf0yjBlmcbTSgYV32M',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1i59E864IJ-AaeuamOc9YpLLEDYWtVZi5Q9CbGJm-Rmc',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1wmdzz7a1v8lIKgjNFCVtm6_P_AohgT5Y9prHufiG4dk',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'emVM1',
          type: 'email',
          label: {
            current: 'Yahoo Mail',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'tVF1',
      label: {
        current: 'Vodafone',
        altFilename: null,
        legacy: [null],
      },
      type: 'telecom',
      groupLabel: 'Vodafone',
      hasOpCom: true,
      opComLabel: 'Vodafone UK',
      isPrevScored: true,
      firstIndex: 2015,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '1FwJrdsdWXC1A4bSohbFWAPyeVIiS4g3Mjm_1Kl09i1E',
      urlCurrentInputSheet: '1llXYKD5fVPp9z78SRDkpw5Zc2krIBcOs_bx3jOUK0qE',
      urlPrevOutputSheet: '114H9ADnPen_mRUnpAu9Ppdf97QIJ2HCwnHb_Ik6majU',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1gDVS-9jltEoEgfWmsQAIcYVnEZK1rpEhur-uD60_Qco',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'mbVF1',
          type: 'mobile',
          subtype: 'prepaid',
          label: {
            current: 'Prepaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'mbVF2',
          type: 'mobile',
          subtype: 'postpaid',
          label: {
            current: 'Postpaid mobile',
            legacy: [null],
          },
        },
        {
          id: 'bbVF1',
          type: 'broadband',
          label: {
            current: 'Fixed-line broadband',
            legacy: [null],
          },
        },
      ],
    },
    {
      id: 'iYA1',
      label: {
        current: 'Yandex',
        altFilename: null,
        legacy: [null],
      },
      type: 'internet',
      groupLabel: 'Yandex (Group)',
      hasOpCom: false,
      opComLabel: null,
      isPrevScored: true,
      firstIndex: 2017,
      columnPrevOutcomeStart: 'Z',
      columnPrevOutcomeEnd: 'AD',
      urlPrevInputSheet: '1Svrmp9T0JgdETzJ8Opo5WOyVomjxHip691ixlwbPtA8',
      urlCurrentInputSheet: null,
      urlPrevOutputSheet: '1Pemf9q3HlZcXJDfm-10nQNx9oMGtNtHn1mhpvWABHZ4',
      urlCurrentOutputSheet: null,
      urlCurrentFeedbackSheet: null,
      urlPrevDataStoreSheet: '1D_188l__7GMlMIG7g6JUTxfxkqAzc1GtnxeyobppLCE',
      urlCurrentDataStoreSheet: null,
      services: [
        {
          id: 'emYA1',
          type: 'email',
          label: {
            current: 'Yandex Mail',
            legacy: [null],
          },
        },
        {
          id: 'seYA1',
          type: 'search',
          label: {
            current: 'Yandex Search',
            legacy: [null],
          },
        },
        {
          id: 'clYA1',
          type: 'cloud',
          label: {
            current: 'Yandex Disk',
            legacy: [null],
          },
        },
      ],
    },
  ],
}
