let EditorsObj = {
  S01: [
    ['zhang@rankingdigitalrights.org'],
    ['rogoff@rankingdigitalrights.org'],
    ['rydzak@rankingdigitalrights.org'],
    ['abrougui@rankingdigitalrights.org'],
    ['wessenauer@rankingdigitalrights.org'],
    ['ucciferri@rankingdigitalrights.org'],
    ['rochefort@rankingdigitalrights.org'],
    ['bojanperkov@sharedefense.org'],
    ['dumitrita.cji@gmail.com'],
    ['zsbchow@gmail.com'],
    ['michael.kowen@gmail.com'],
    ['opeakanbi@gmail.com'],
    ['museofu@gmail.com'],
    ['milabajiic@gmail.com'],
    ['jiyounchoe915@gmail.com'],
    ['tatyana.lockot@gmail.com'],
  ],
  S02: [
    ['zhang@rankingdigitalrights.org'],
    ['rogoff@rankingdigitalrights.org'],
    ['rydzak@rankingdigitalrights.org'],
    ['abrougui@rankingdigitalrights.org'],
    ['wessenauer@rankingdigitalrights.org'],
    ['ucciferri@rankingdigitalrights.org'],
    ['rochefort@rankingdigitalrights.org'],
    ['bojanperkov@sharedefense.org'],
    ['dumitrita.cji@gmail.com'],
    ['zsbchow@gmail.com'],
    ['michael.kowen@gmail.com'],
    ['opeakanbi@gmail.com'],
    ['museofu@gmail.com'],
    ['milabajiic@gmail.com'],
    ['jiyounchoe915@gmail.com'],
    ['tatyana.lockot@gmail.com'],
  ],

  S03: [
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
  ],
}

// var editorsVector = [
//     ["zhang@rankingdigitalrights.org"],
//     ["lauraannreed@gmail.com"],
//     ["luisgar12@gmail.com"],
//     ["dumitrita.cji@gmail.com"],
//     ["rogoff@rankingdigitalrights.org"],
//     ["elonnaiz@gmail.com"],
//     ["michael.kowen@gmail.com"],
//     ["elonnaiz@gmail.com"],
//     ["ahackl2130@gmail.com"],
//     ["mariam@smex.org"],
//     ["rydzak@rankingdigitalrights.org"],
//     ["ahackl2130@gmail.com"],
//     ["museofu@gmail.com"],
//     ["itskermoshina@gmail.com"],
//     ["opeakanbi@gmail.com"],
//     ["alex.comninos@gmail.com"],
//     ["moussa@smex.org"],
//     ["abrougui@rankingdigitalrights.org"],
//     ["8kkim8@gmail.com"],
//     ["lucia@karisma.org.co"],
//     ["outi.puukko@gmail.com"],
//     ["zsbchow@gmail.com"],
//     ["wessenauer@rankingdigitalrights.org"],
//     ["amy.mcewan.s@googlemail.com"],
//     ["bojanperkov@sharedefense.org"],
//     ["tatyana.lockot@gmail.com"]
// ]
